name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Il nome della tua branch principale, potrebbe essere 'master' o un altro nome

jobs:
  build:
    runs-on: ubuntu-latest # Utilizzeremo un runner su Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Prende il codice dal repository

      - name: Set up Node.js
        uses: actions/setup-node@v2 # Imposta l'ambiente Node.js
        with:
          node-version: "16" # Usa la versione di Node.js che desideri (ad esempio, 16)

      - name: Install dependencies
        run: npm install # Installa le dipendenze con npm

      - name: Build the project
        run: npm run build # Esegui il build del progetto (con Vite)

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # Azione che gestisce il deploy su GitHub Pages
        with:
          branch: gh-pages # La branch su cui pubblicare il sito (la branch di GitHub Pages)
          folder: dist # La cartella che contiene il build finale dell'app (in Vite, di solito è 'dist')

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Usa il token GitHub segreto che GitHub fornisce automaticamente
